# Generated by Django 3.2 on 2023-07-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terremotito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intensidad',
            name='tiempo',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
